# Generated by Django 5.2.2 on 2025-06-14 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("locality", models.CharField(max_length=200)),
                ("city", models.CharField(max_length=50)),
                ("mobile", models.IntegerField(default=0)),
                ("zipcode", models.IntegerField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("PB", "Punjab"),
                            ("SD", "Sindh"),
                            ("KP", "Khyber Pakhtunkhwa"),
                            ("BL", "Balochistan"),
                            ("GB", "Gilgit-Baltistan"),
                            ("IS", "Islamabad Capital Territory"),
                            ("AJK", "Azad Jammu and Kashmir"),
                        ],
                        max_length=108,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
